language: node_js

cache: yarn

node_js:
  - 8
  - 10

notifications:
  email: false

branches:
  only:
    - master
  except:
    - /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: deploy
      script: yarn release

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add codecov

script:
  - yarn test --coverage
  - codecov
